package freeart;
// Generated 9 janv. 2015 14:45:14 by Hibernate Tools 3.2.1.GA



/**
 * Categorie generated by hbm2java
 */
public class Categorie  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String description;

    public Categorie() {
    }

    public Categorie(String nom, String description) {
       this.nom = nom;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


