package freeart;
// Generated 9 janv. 2015 14:45:14 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Creation generated by hbm2java
 */
public class Creation  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String description;
     private byte[] file;
     private int idCategorie;
     private int idUser;
     private Date date;
     private String dimensFile;
     private int poidsFile;

    public Creation() {
    }

    public Creation(String nom, String description, byte[] file, int idCategorie, int idUser, Date date, String dimensFile, int poidsFile) {
       this.nom = nom;
       this.description = description;
       this.file = file;
       this.idCategorie = idCategorie;
       this.idUser = idUser;
       this.date = date;
       this.dimensFile = dimensFile;
       this.poidsFile = poidsFile;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }
    public int getIdCategorie() {
        return this.idCategorie;
    }
    
    public void setIdCategorie(int idCategorie) {
        this.idCategorie = idCategorie;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDimensFile() {
        return this.dimensFile;
    }
    
    public void setDimensFile(String dimensFile) {
        this.dimensFile = dimensFile;
    }
    public int getPoidsFile() {
        return this.poidsFile;
    }
    
    public void setPoidsFile(int poidsFile) {
        this.poidsFile = poidsFile;
    }




}


