package freeart;
// Generated 9 janv. 2015 14:45:14 by Hibernate Tools 3.2.1.GA



/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private int idCreation;

    public Tag() {
    }

    public Tag(String nom, int idCreation) {
       this.nom = nom;
       this.idCreation = idCreation;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public int getIdCreation() {
        return this.idCreation;
    }
    
    public void setIdCreation(int idCreation) {
        this.idCreation = idCreation;
    }




}


